### ISSUE TITLE
Optimize one branch length

### ISSUE THREAD

**Issue by matsen** [matsengrp/pt#2]
The libpll docs have [a really nice example](https://github.com/xflouris/libpll/tree/dev/examples/newton) of doing Newton's method.

They apparently thought it would be clearer to write out the operations directly rather than getting them from using a traversal. However we can just do a traversal as in `FullTraversalLogLikelihood` and get the needed operations, it seems. Perhaps we'll want to stop one operation short of the end? ~~You'll need to work out exactly which branch this will correspond to: my guess is between `tree` and `tree->next`, but we'll have to sort that out.~~ There are [docs on tree traversing](https://github.com/xflouris/libpll/wiki/API-Reference-%28Tree-Module%29#pll_utree_traverse_apply). 

The test for this will be to see if we can get back the same branch length that RAxML decided was optimal (after setting it to some other value).

**Comment by matsen** [comment]
Here's an informative GDB session for the three-taxon unrooted tree:

```
(gdb) p tree
$15 = (pll_utree_t *) 0x68c1f0
(gdb) p tree->next
$16 = (pll_utree *) 0x68fb50
(gdb) p tree->next->next
$17 = (pll_utree *) 0x68f980
(gdb) p tree->next->next->next
$18 = (pll_utree *) 0x68c1f0                 <--- note here we've made the full loop
(gdb) p tree->back
$19 = (pll_utree *) 0x68a5d0
(gdb) p tree->back->clv_index
$20 = 0
(gdb) p tree->next->back->clv_index
$21 = 1
(gdb) p tree->next->next->back->clv_index
$22 = 2
(gdb) p tree->clv_index
$23 = 3
(gdb) p tree->next->clv_index
$24 = 3
(gdb) p tree->next->next->clv_index
$25 = 3
```

Thus `next` takes us around an internal node, and all of those have the same CLV index. To leave that internal node, we use `back`.

**Comment by matsen** [comment]
Like so:

![img_20160608_055544](https://cloud.githubusercontent.com/assets/112708/15895064/1b0b7ba6-2d3e-11e6-8eba-9302172b0a35.jpg)

**Comment by matsen** [comment]
Reading

```
typedef struct pll_utree
{
  char * label;
  double length;
  unsigned int clv_index;
  int scaler_index;
  unsigned int pmatrix_index;
  struct pll_utree * next;
  struct pll_utree * back;

  void * data;
} pll_utree_t;
```

it [appears that there should be no difference](http://stackoverflow.com/questions/2630525/redundant-naming-in-c-c-typedefs-structs) `pll_utree` and `pll_utree_t`. Is that right @bcclaywell ?

**Comment by matsen** [comment]
Continuing learning: `tree == tree->back->back`.

If we parse the tree `(a:0.601,b:0.701,c:0.801):0.901;`, running `pll_utree_show_ascii(tree, 255);` gives

```
|
+--- a 0.601000 0 -1 0
|
+--- b 0.701000 1 -1 1
|
+--- c 0.801000 2 -1 2
```

and in the debugger we get this output:

```
(gdb) p tree->length
$33 = 0.60099999999999998     <--- the length of a node is the length of its "back" edge
(gdb) p tree->back->length
$34 = 0.60099999999999998     <--- ditto
(gdb) p tree->next->length
$35 = 0.70099999999999996
(gdb) p tree->back->next      <--- leaves don't have a `next` edge
$36 = (pll_utree *) 0x0
```

**Comment by matsen** [comment]
As far as I could tell, there's no API call to set a branch length, so perhaps it's up to us to set `tree->length` and `tree->back->length`.

So, fortunately, if we traverse the tree in the Newton example, `((0:0.2, 1:0.4):0.6, 2:0.3, 3:0.5);` and ask for operations, it gives us exactly the operations [in the newton.c example](https://github.com/xflouris/libpll/blob/658cb2669472cf18cdb79552db9efc2aa14f6efb/examples/newton/newton.c#L178):

```
(gdb) p operations_[0]
$53 = {
  parent_clv_index = 4,
  parent_scaler_index = 0,
  child1_clv_index = 0,
  child1_matrix_index = 0,
  child1_scaler_index = -1,
  child2_clv_index = 1,
  child2_matrix_index = 1,
  child2_scaler_index = -1
}
(gdb) p operations_[1]
$54 = {
  parent_clv_index = 5,
  parent_scaler_index = 1,
  child1_clv_index = 2,
  child1_matrix_index = 2,
  child1_scaler_index = -1,
  child2_clv_index = 3,
  child2_matrix_index = 3,
  child2_scaler_index = -1
}
```

Thus, we should be able to get exactly the output of `newton.c` from running a branch length optimization scheme on that branch.

**Comment by bcclaywell** [comment]
> it appears that there should be no difference pll_utree and pll_utree_t. Is that right @bcclaywell ?

Correct. The difference between the two is that `pll_utree_t` is a typedef for `struct pll_utree`. That is, if you wanted to instantiate a `pll_utree` you'd have to actually type `struct` out in front of it. Not so with `pll_utree_t`.
