### ISSUE TITLE
Optimize all branch lengths

### ISSUE THREAD

**Issue by matsen** [matsengrp/pt#3]
What needs to happen to optimize all of the branch lengths of the tree, from what I know now.
1. Play around with the tree traversal functions and look where they take us. #2 should be helpful here. Does  [utree traversal function](https://github.com/xflouris/libpll/blob/e47b400b2d357e948c60cc7b2cc6aa210069ad21/src/utree.c#L309) effectively visit every internal edge twice?
2. Generalize the OptimizeCurrentBranch to take a `pll_utree_t` argument that indicates the branch to be optimized.
3. Wrap this method to into a callback function to the utree traversal function.
4. Repeat until most branch lengths don't change upon executing this function.

The test for this will be to see if we can get back the RAxML-inferred branch lengths in `test-data/five`. And other tests!

**Comment by matsen** [comment]
This is done, no?

**Comment by thayerf** [comment]
Yes, it is.
