### ISSUE TITLE
How to keep track of visited trees, with an eye towards multithreading?

### ISSUE THREAD

**Issue by matsen** [matsengrp/pt#5]
We need a way of remembering which trees we have visited, and information about them (perhaps just the ML likelihood?). Trees will be keyed by their sorted Newick topology strings (no branch lengths), unless we can come up with something more clever.

It sure seems to me that this application is asking to be multithreaded. Thus we need a non-locking central store of topologies.

[junction](https://github.com/preshing/junction) appears to fit the bill. 

Thoughts, @cwhidden @bcclaywell?

**Comment by bcclaywell** [comment]
My first impression is that Junction is overcomplicated. It depends on an abstraction layer called Turf, and Turf is kind of scary. A comment on his [blog post about Junction](http://preshing.com/20160201/new-concurrent-hash-maps-for-cpp/) complained of a compilation error, and [his reply](http://preshing.com/20160201/new-concurrent-hash-maps-for-cpp/#IDComment1014696367) was:

> Looks like there is another project defining operator new besides Turf. You can disable Turf's using CMake. Just set TURF_REPLACE_OPERATOR_NEW to 0.

Call me old-fashioned but redefining `operator new` by default just to get a lock-free map is terrifying.

Someone else in the comments said they were using [libcuckoo](https://github.com/efficient/libcuckoo), which looks pretty nice and built easily for me. The Junction author also added libcuckoo to his test suite and concluded that its performance was ["pretty darn good"](http://preshing.com/20160201/new-concurrent-hash-maps-for-cpp/#IDComment1011877463):

![](http://preshing.com/images/concurrent-map-graph-libcuckoo.png)

**Comment by matsen** [comment]
👍 for libcuckoo!
